name: Continuous Integration client

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: ğŸ“€ Add yarn
        run: cd client && yarn install

      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: ğŸ¨ Check code formatting
        run: cd client && yarn fix

      - name: ğŸ“ Lint code
        run: cd client && yarn lint


      - name: ğŸª„ Run tests in client
        run:  cd client && yarn test

      - name: ğŸ“¦ Build client
        run: cd client && yarn tsc --noEmit